name: Inforadio Feed Update
run-name: Inforadio Feed Update
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  Run-Playwright:
    name: Run Playwright
    runs-on: ubuntu-latest
    container:
      image: pennyvault/playwright-go
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Verify files are checked out
        run: ls -l 
